catalog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tables/', views.TableListView.as_view(), name='tables'),
    path('table/<int:pk>', views.TableDetailView.as_view(), name='table-detail'),
    path('foods/', views.FoodListView.as_view(), name='foods'),
    path('food/<int:pk>', views.FoodDetailView.as_view(), name='food-detail'),
    path('drinks/', views.DrinkListView.as_view(), name='drinks'),
    path('drink/<int:pk>', views.DrinkDetailView.as_view(), name='drink-detail'),
]
urlpatterns += [   
    path('book/<uuid:pk>/renew/', views.renew_table_restoran, name='renew-table-restoran'),
]

restoran/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
# Use include() to add paths from the catalog application 
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models

# Create your models here.
class Type(models.Model):

    name = models.CharField(max_length=200, help_text='Enter a food type (e.g. Asian)')
    
    def __str__(self):

        return self.name

from django.urls import reverse 

class Food(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    name = models.CharField(max_length=200)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the food")
    Cost = models.CharField('Cost',max_length=13, unique=True, help_text='Enter a cost of the food')
    Type = models.ForeignKey('Type', on_delete=models.SET_NULL, null=True)
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    
    def _str_(self):
        """
        String for representing the Model object.
        """
        return self.name
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('food-detail', args=[str(self.id)])
import uuid # Required for unique book instances
from datetime import date 

from django.contrib.auth.models  import User


class Drink(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    name = models.CharField(max_length=200)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the drink")
    Cost = models.CharField('Cost',max_length=13, unique=True, help_text='Enter a cost of the drink')
    Type = models.ForeignKey('Type', on_delete=models.SET_NULL, null=True)
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    
    def _str_(self):
        """
        String for representing the Model object.
        """
        return self.name
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('drink-detail', args=[str(self.id)])
import uuid # Required for unique book instances
from datetime import date 

from django.contrib.auth.models  import User



class Table(models.Model):

    number = models.CharField(max_length=200)
    
    def __str__(self):

        return self.number
    
    def get_absolute_url(self):

        return reverse('table-detail', args=[str(self.id)])

import uuid 

class TableInstance(models.Model):

    table = models.ForeignKey('Table', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


    LOAN_STATUS = (
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Table availability')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set table as returned"),)   
        

    def _str_(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id,self.table.number)

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewTableForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        # Check if a date is not in the past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Food, Table, TableInstance, Type, Drink

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_tables = Table.objects.all().count()
    num_instances = TableInstance.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = TableInstance.objects.filter(status__exact='a').count()
  # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=None)

from django.views import generic

class TableListView(generic.ListView):
    model = Table 
   
class TableDetailView(generic.DetailView):
    model = Table    

class FoodListView(generic.ListView):
    model = Food

class FoodDetailView(generic.DetailView):
    model = Food      

class DrinkListView(generic.ListView):
    model = Drink

class DrinkDetailView(generic.DetailView):
    model = Drink  
    
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalog.forms import RenewTableForm

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_table_restoran(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    table_instance = get_object_or_404(TableInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewTableForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            table_instance.due_back = form.cleaned_data['renewal_date']
            table_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewTableForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'table_instance': table_instance,
    }

    return render(request, 'catalog/table_renew_restoran.html', context)    

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Welcome to Euphoria</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Добавление дополнительного статического CSS файла --> 
<nav class="navigation">
  <ul>
    <li><a href="{% url 'index' %}">Euphoria</a></li><!--
    --><li><a href="{% url 'foods' %}">Kitchen</a></li><!--
    --><li><a href="{% url 'drinks' %}">Bar</a></li><!--
    --><li><a href="{% url 'tables' %}">Reserve</a></li>

  </ul>
</nav>
<style>
  .navigation li {
  display: inline-block;
    font-family: 'William', Brush Script MT, Brush Script Std, cursive;
}
.navigation a {
  background: #395870;
  background: transparent;
  border-right: 1px solid rgba(0, 0, 0, .3);
  color: #fff;
  padding: 18px 30px;
  text-decoration: none;
  font-size: 30px;
  text-align: center;
}
.navigation a:hover {
  background: transparent;
  box-shadow: inset 0 0 10px 1px rgba(0, 0, 0, .3);
}
.navigation li:first-child a {
  border-radius: 4px 0 0 4px;
}
.navigation li:last-child a {
  border-right: 0;
  border-radius: 0 4px 4px 0;
}
</style>
</body>
<style type="text/css">
  body {
  margin: 0;
  padding: 0;
  width:100vw;
  height: 100vh;
  background-color: #eee;
}
.content {
  display: flex;
  justify-content: center;
  align-items: center;
  width:100%;
  height:100%;
}
.loader-wrapper {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  background-color: #242f3f;
  display:flex;
  justify-content: center;
  align-items: center;
}
.loader {
  display: inline-block;
  width: 30px;
  height: 30px;
  position: relative;
  border: 4px solid #Fff;
  animation: loader 3s infinite ease;
}
.loader-inner {
  vertical-align: top;
  display: inline-block;
  width: 100%;
  background-color: #fff;
  animation: loader-inner 3s infinite ease-in;
}
@keyframes loader {
  0% { transform: rotate(0deg);}
  25% { transform: rotate(180deg);}
  50% { transform: rotate(180deg);}
  75% { transform: rotate(360deg);}
  100% { transform: rotate(360deg);}
}
@keyframes loader-inner {
  0% { height: 0%;}
  25% { height: 0%;}
  50% { height: 100%;}
  75% { height: 100%;}
  100% { height: 0%;}
}
</style>

      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
         {% block pagination %}
           {% if is_paginated %}
            <div class="pagination">
             <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
             </span>
            </div>
           {% endif %}
          {% endblock %} 
      </div>
    </div>

  </div>
</body>

</html>

catalog/templates/catalog/drink_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ drink.name }}</h1>

  <p><strong>Summary:</strong><a href="">{{ drink.summary }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Cost:</strong>={{ drink.cost }}</p> 
  <p><strong>Type:</strong> {{ drink.type.all|join:", " }}</p>  

  <div style="margin-left:20px;margin-top:20px">

  </div>
{% endblock %}

catalog/templates/catalog/drink_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Bar</h1>
  <style>
    body{
       background-image: url('https://www.quay.com.au/wp-content/uploads/2018/07/Banner-Image-6.jpg');
      background-repeat: no-repeat;
      image 
}
</style>
<style>
    h1 {
  font-size: 50px;
  text-align: center;
  text-transform: uppercase;
  font-style: italic;
  font-family: 'William', sans-serif;
  margin-bottom: 0;
  margin-top:0;
  padding-top: 35x;
  color: white; 
}
</style>
<ul class="dotted">
  <p>Cold Drinks</p>
  <li><span>Coca Cola</span><span>590 tg</span></li>
  <li><span>Sprite</span><span>590 tg</span></li>
  <li><span>Fanta</span><span>590 tg</span></li>
  <li><span>Pepsi</span><span>590 tg</span></li>

  <p>Hot Drinks</p>
  <li><span>Berry tea</span><span>1000 tg</span></li>
 <li><span>Americano</span><span>700 tg</span></li>
  <li><span>Latte</span><span>900 tg</span></li>
  <li><span>Raf</span><span>900 tg</span></li>
  <li><span>Cappuccino</span><span>1000 tg</span></li>
</ul>
<style>
  .dotted {
list-style: none;
font-family: 'Marck Script', cursive;
}
.dotted li {
margin-bottom: 5px;
border-bottom: 2px #404B51 dotted;
font-size: 26px;
line-height: 1;
}
.dotted li span:nth-child(odd) {
padding-right: 6px; 
color: #35D1CE;
}
.dotted li span:nth-child(even) {
float: right; 
padding-left: 6px;
color: #35D1CE;
}
.dotted span {
background: transparent;
position: relative;
bottom: -7px;
}
p {
  color: #35D1CE;
  font-size: 30px;
  text-align: center;
}
</style>
{% endblock %}

catalog/templates/catalog/food_detail.html
{% extends "base_generic.html" %}

{% block content %}


<style>
body {
  background-image: url('https://realfood.tesco.com/media/images/1400x919-SpaghettiCarbonara-557b6ff5-c4f3-4565-ae8e-a506f7dcc415-0-1400x919.jpg');
  background-repeat: no-repeat;
}
</style>
<style type="text/css">
   .space { 
    padding: 50px; /* Поля */
    background: transparent; /* Цвет фона */
    border: 2px solid transparent; /* Параметры рамки */
    width: 900px;
    margin: 200px;
    text-align: center;
    font-size: 20px;
    color: white;
   }
  </style>
 </head>
<body>
  <div class="space">
    <h2>Summary</h2>
    <h3></h3>
      <h4>Name: {{ food.name }}</h4>
<p><strong></strong>{{ food.summary }}</p> 
  </div>
 </body>

<style>
	p{
   color: white;
  font-size: 20px;
  text-align: center;
  font-family: 'William', Brush Script Std;
}
 h4{
  font-size: 30px;
  text-transform: none;
  font-style: italic;
  font-family: 'William', sans-serif;
  margin-bottom: 0;
  margin-top:0;
  padding-top: 35x;
  color: white; 
 }
  </div>
{% endblock %}

catalog/templates/catalog/food_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Menu</h1>
<style>
body {
  background-image: url('https://www.quay.com.au/wp-content/uploads/2019/07/Marron-and-Flowers.jpg');
  background-repeat: no-repeat;
}
</style>
      <style>
    h1 {
  font-size: 50px;
  text-align: center;
  text-transform: uppercase;
  font-style: italic;
  font-family: 'William', sans-serif;
  margin-bottom: 0;
  margin-top:0;
  padding-top: 35x;
  color: #FFCFF1; 
}
</style>
<ul class="dotted">
<p>Pasta</p> 

{% for food in food_list %}
      <li>
        <a href="{{ food.get_absolute_url }}">{{ food.name }}</a><span>1890tg</span>
      </li>
    {% endfor %}

<li><span>Pasta with anchovies</span><span>2100 tg</span></li>
<li><span>Amatrice spaghetti</span><span>2100 tg</span></li>
<li><span>Fresh tomato & basil sauce (Pomarola)</span><span>2200 tg</span></li>

<p>Snacks</p>
<li><span>Potato fries</span><span>499 tg</span></li>
<li><span>Cracker nuts</span><span>501 tg</span></li>
<li><span>Bitter ballen</span><span>600 tg</span></li>
<li><span>Patato chips</span><span>599 tg</span></li>

<p>Salads</p>
<li><span>Arab salad</span><span>1200 tg</span></li>
<li><span>Chef salad</span><span>1500 tg</span></li>
<li><span>Chicken salad</span><span>1700 tg</span></li>

<p>Fast-food</p>
<li><span>Burger</span><span>1900 tg</span></li>
<li><span>Pizza</span><span>1900 tg</span></li>
<li><span>Chicken nuggets</span><span>1200 tg</span></li>  
</ul>
<style>
  .dotted {
list-style: none;
font-family: 'Marck Script', cursive;
}
.dotted li {
margin-bottom: 5px;
border-bottom: 2px #404B51 dotted;
font-size: 26px;
line-height: 1;
}
.dotted li span:nth-child(odd) {
padding-right: 6px; 
color: #436CB9;
}
.dotted li span:nth-child(even) {
float: right; 
padding-left: 6px;
color: #436CB9;
}
.dotted span {
background: transparent;
position: relative;
bottom: -7px;
}
p {
  color: #C53151;
  font-size: 30px;
  text-align: center;
  font-family: 'William', Brush Script Std;
}
</style>
      
{% endblock %}

catalog/templates/catalog/table_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Table {{ table.number }}</h1>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Frees</h4>

    {% for free in table.tableinstance_set.all %}
      <hr>
      <p class="{% if free.status == 'a' %}text-success{% elif free.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ free.get_status_display }}
      </p>
      {% endfor free.status != 'a' %}
        <p><strong>Due to be returned</strong> {{ free.due_back }}</p>
  </div>
{% endblock %}`

catalog/templates/catalog/table_instance_list_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Tables</h1>

    {% if tableinstance_list %}
    <ul>

      {% for tableinst in tableinstance_list %} 
      <li class="{% if tableinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'table-detail' tableinst.table.pk %}">{{tableinst.table.number}}</a> ({{ tableinst.due_back }}) {% if user.is_staff %}- {{ tableinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-table-restoran' tableinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no tables borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/table_instance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed tables</h1>

    {% if tableinstance_list %}
    <ul>

      {% for tablinst in tableinstance_list %} 
      <li class="{% if tableinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'table-detail' tableinst.table.pk %}">{{tableinst.table.number}}</a> ({{ tableinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no tables borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/table_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1></h1>
 <style>
body {
  background-image: url('https://marketkitchen.com/files/015d27e2a7a034ef84312c9e677d36b6_full_size.jpg');
  background-repeat: no-repeat;
}
</style>
<ul class="dotted">
  <p>Dlya smerthnyh</p>
  <li><span>Table 1(4 people)</span><span>2000 tg/hour</span></li>
  <li><span>Table 2(4 people)</span><span>2000 tg/hour</span></li>
  <li><span>Table 3(6 people)</span><span>2500 tg/hour</span></li>
  <li><span>Table 4(6 people)</span><span>2500 tg/hour</span></li>
  <li><span>Table 5(10 people)</span><span>3000 tg/hour</span></li>
 <li><span>Table 6(10 peolpe)</span><span>3000 tg/hour</span></li>
  <p>VIP</p>
  <li><span>Room 1</span><span>5000 tg/hour</span></li>
  <li><span>Room2</span><span>5000 tg/hour</span></li>
  <li><span>Room3</span><span>5000 tg/hour</span></li>
</ul>
<style>
  .dotted {
list-style: none;
font-family: 'Marck Script', cursive;
}
.dotted li {
margin-bottom: 5px;
border-bottom: 2px white dotted;
font-size: 30px;
line-height: 1;
}
.dotted li span:nth-child(odd) {
padding-right: 6px; 
color: white;
}
.dotted li span:nth-child(even) {
float: right; 
padding-left: 6px;
color: white;
}
.dotted span {
background: transparent;
position: relative;
bottom: -7px;
}
p {
  color: white;
  font-size: 30px;
  text-align: center;
}
</style>
      
{% endblock %}

catalog/templates/catalog/table_renew _restoran.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ table_instance.table.number }}</h1>
  <p>Borrower: {{ table_instance.borrower }}</p>
  <p{% if table_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ table_instance.due_back }}</p>
    
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

  <h1></h1>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
<style>
  body {
  background-image: url("https://i0.wp.com/www.driftwoodjournals.com/wp-content/uploads/2018/04/IMG_5107.jpg?resize=1300%2C866&ssl=1");
  background-repeat: no-repeat;
}
</style>
<style type="text/css">
   .space { 
    padding: 50px; /* Поля */
    background: transparent; /* Цвет фона */
    border: 2px solid transparent; /* Параметры рамки */
    width: 900px;
    margin: 200px;
    text-align: center;
    font-size: 20px;
    color: white;
   }
  </style>
 </head>
 <body>
  <div class="space">
    <h2>About us</h2>
    <h3></h3>
    <h4></h4>
   May your Euphoria be with us.We will show you the real taste of real food.
   Come and have a taste of anything and you won't leave us
  </div>
 </body>

<body>
      <style>
    h2 {
  font-size: 30px;
  text-align: center;
  text-transform: uppercase;
  font-style: italic;
  font-family: 'William', Brush Script Std;
  margin-bottom: 0;
  margin-top:0;
  padding-top: 35x;
  color: white; 
}
</style>

</body>

{% endblock %}